import { ps } from '@sourcegraph/cody-shared'

export const PROMPT_TOPICS = {
    OUTPUT: ps`CODE5711`,
    SELECTED: ps`SELECTEDCODE7662`,
    PRECEDING: ps`PRECEDINGCODE3493`,
    FOLLOWING: ps`FOLLOWINGCODE2472`,
    INSTRUCTIONS: ps`INSTRUCTIONS7390`,
    DIAGNOSTICS: ps`DIAGNOSTICS5668`,
    FILENAME: ps`TESTFILE7041`,
}
