/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import com.sourcegraph.cody.protocol_generated.CodyAgentServer
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest: CodyAgentServer? = null
        println(classUnderTest)
    }
}
