/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LogEntry {
  level: "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE"
  target: string
  message: string
  file?: string
  line?: number
}
export declare class Sysproxy {
  enable: boolean
  host: string
  port: number
  bypass: string
}
export declare namespace log {
  export function init(callback: (entry: LogEntry) => void): void
}
export declare namespace test {
  export function log(): void
}
export declare namespace config {
  export function systemProxy(): Sysproxy | null
  export function caCerts(bundledCerts?: Array<string> | undefined | null): Array<string>
}
