export const DefaultShellContextConfig = {
    allow: ['*'],
    block: [
        'rm',
        'chmod',
        'shutdown',
        'history',
        'user',
        'sudo',
        'su',
        'passwd',
        'chown',
        'chgrp',
        'kill',
        'reboot',
        'poweroff',
        'init',
        'systemctl',
        'journalctl',
        'dmesg',
        'lsblk',
        'lsmod',
        'modprobe',
        'insmod',
        'rmmod',
        'lsusb',
        'lspci',
    ],
}
