export const GENERAL_HELP_LABEL = 'Search for a file to include, or type # for symbols...'
export const FILE_HELP_LABEL = 'Search for a file to include...'
export const SYMBOL_HELP_LABEL = 'Search for a symbol to include...'
export const NO_SYMBOL_MATCHES_LABEL = 'No symbols found'
export const NO_FILE_MATCHES_LABEL = 'No files found'
export const NO_SYMBOL_MATCHES_HELP_LABEL = ' (language extensions may be loading)'
export const PACKAGE_HELP_LABEL = 'Search for a package to include...'
export const NO_PACKAGE_MATCHES_LABEL = 'No packages found'
export const FILE_RANGE_TOOLTIP_LABEL = 'Type a line range to include, e.g. 5-10...'
export const LARGE_FILE_WARNING_LABEL =
    'File too large. Add line range with : or use @# to choose a symbol'
export const IGNORED_FILE_WARNING_LABEL = 'Ignored due to Enterprise configuration setting'

export const QUICK_PICK_ITEM_EMPTY_INDENT_PREFIX = '\u00A0\u00A0\u00A0\u00A0\u00A0'
export const QUICK_PICK_ITEM_CHECKED_PREFIX = '$(check)'
