import { isMacOS } from '@sourcegraph/cody-shared'

const osIcon = isMacOS() ? '⌥' : 'Alt+'

export const CodyCommandMenuItems = [
    {
        key: 'ask',
        description: 'New Chat',
        prompt: 'Start a new chat',
        icon: 'comment',
        command: { command: 'cody.chat.panel.new' },
        keybinding: `${osIcon}L`,
        mode: 'ask',
        type: 'default',
    },
    {
        key: 'edit',
        description: 'Edit Code',
        prompt: 'Start a code edit',
        icon: 'wand',
        command: { command: 'cody.command.edit-code' },
        keybinding: `${osIcon}K`,
        mode: 'edit',
        type: 'default',
    },
    {
        key: 'doc',
        description: 'Document Code',
        icon: 'book',
        command: { command: 'cody.command.document-code' },
        keybinding: `${osIcon}D`,
        mode: 'edit',
        type: 'default',
    },
    {
        key: 'explain',
        description: 'Explain Code',
        icon: 'file-binary',
        command: { command: 'cody.command.explain-code' },
        keybinding: '',
        mode: 'ask',
        type: 'default',
    },
    {
        key: 'test',
        description: 'Generate Unit Tests',
        icon: 'package',
        command: { command: 'cody.command.unit-tests' },
        keybinding: '',
        mode: 'edit',
        type: 'default',
    },
    {
        key: 'smell',
        description: 'Find Code Smells',
        icon: 'checklist',
        command: { command: 'cody.command.smell-code' },
        keybinding: '',
        mode: 'ask',
        type: 'default',
    },
    {
        key: 'search',
        prompt: 'Start a new natural language search',
        description: 'Search Code (Beta)',
        icon: 'search',
        command: { command: 'cody.symf.search' },
        keybinding: '',
        type: 'default',
    },
    {
        key: 'commit',
        description: 'Generate Commit (Experimental)',
        icon: 'git-commit',
        command: { command: 'cody.command.generate-commit' },
        keybinding: '',
        type: 'default',
        configuration: 'cody.internal.unstable',
    },
    {
        key: 'custom',
        description: 'Custom Commands',
        icon: 'tools',
        command: { command: 'cody.menu.custom-commands' },
        keybinding: `${osIcon}⇧C`,
        type: 'default',
        contextValue: 'cody.sidebar.custom-commands',
    },
]
