name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - uses: sourcegraph/backport@v2
        with:
          github_token: ${{ secrets.BACKPORT_GITHUB_TOKEN }}
          # TODO: Remove the jb, vscode parts of the pattern after VSCode v1.66 and JetBrains v7.66 reach stable
          label_pattern: '^backport (?<base>((jb|vscode)-v\d+\.\d+\.x)|(M\d+))$'
          team_reviews: "cody-core"
