# See https://sourcegraph.com/docs/dev/background-information/ci#pr-auditor
name: pr-auditor
on:
  pull_request_target:
    types: [closed, edited, opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "sourcegraph/devx-service"
          token: ${{ secrets.PR_AUDITOR_TOKEN }}
      - uses: actions/setup-go@v4
        with: { go-version: "1.22" }

      - run: "go run ./cmd/pr-auditor"
        env:
          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
          GITHUB_TOKEN: ${{ secrets.PR_AUDITOR_TOKEN }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
