name: Sourcegraph
on:
  push:
    paths:
      - '**.kt'
      - '**.java'
      - '**.kts'
      - '.github/workflows/scip-java.yml'
jobs:
  scip-java:
    if: github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    name: "Upload SCIP"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-
          restore-keys: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-k
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: coursier/setup-action@v1
        with:
          jvm: 'zulu:17'
          apps: scip-java
      - name: Generate SCIP File
        run: |
          pushd jetbrains
          scip-java index --build-tool=gradle
          popd > /dev/null

      - name: Install src
        run: yarn global add @sourcegraph/src

      - name: Upload SCIP to Cloud
        run: |
          pushd jetbrains
          src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
          popd > /dev/null
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}

      - name: Upload SCIP to S2
        run: |
          pushd jetbrains
          src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
          popd > /dev/null
        env:
          SRC_ENDPOINT: https://sourcegraph.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}
