name: vscode-insiders-release

on:
  workflow_dispatch:

jobs:
  release:
    if: github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
        with:
          run_install: true
      - run: pnpm build
      - run: pnpm run test
      - run: xvfb-run -a pnpm -C vscode run test:integration
      - run: xvfb-run -a pnpm -C vscode run test:e2e
        env:
          NO_LOG_TESTING_TELEMETRY_CALLS: true
      - run: CODY_RELEASE_TYPE=insiders pnpm -C vscode run release
        id: create_release
        if: github.repository == 'sourcegraph/cody'
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          VSCODE_OPENVSX_TOKEN: ${{ secrets.VSCODE_OPENVSX_TOKEN }}
      - name: Tag insiders release
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.create_release.outputs.version_tag }}",
              sha: context.sha
            })
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # SECURITY: pin third-party action hashes
        env:
          SLACK_CHANNEL: wg-cody-vscode
          SLACK_ICON: https://github.com/sourcegraph.png?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Insiders build failed
          SLACK_COLOR: danger
          SLACK_FOOTER: ""
          MSG_MINIMAL: actions url
