@file:Suppress("unused", "ConstPropertyName")
package com.sourcegraph.cody.protocol_generated

object Constants {
  const val error = "error"
  const val warning = "warning"
  const val information = "information"
  const val IDEEXTENSION = "IDEEXTENSION"
  const val `tree-sitter` = "tree-sitter"
  const val indentation = "indentation"
  const val Automatic = "Automatic"
  const val Invoke = "Invoke"
  const val human = "human"
  const val assistant = "assistant"
  const val isChatErrorGuard = "isChatErrorGuard"
  const val chat = "chat"
  const val editor = "editor"
  const val menu = "menu"
  const val sidebar = "sidebar"
  const val `code-action_explain` = "code-action:explain"
  const val `code-action_document` = "code-action:document"
  const val `code-action_edit` = "code-action:edit"
  const val `code-action_fix` = "code-action:fix"
  const val `code-action_generate` = "code-action:generate"
  const val `custom-commands` = "custom-commands"
  const val test = "test"
  const val `code-lens` = "code-lens"
  const val explain = "explain"
  const val unit = "unit"
  const val smell = "smell"
  const val terminal = "terminal"
  const val doc = "doc"
  const val primary = "primary"
  const val secondary = "secondary"
  const val icon = "icon"
  const val none = "none"
  const val streaming = "streaming"
  const val disabled = "disabled"
  const val enabled = "enabled"
  const val notification = "notification"
  const val request = "request"
}
